version: '3'

services:
  tapo-exporter:
    image: tapo-exporter
    volumes:
       - ./tapo.yml:/app/tapo.yaml:ro
    ports:
      - 9333:9333
    environment:
      - TAPO_EMAIL=${tapo_email}
      - TAPO_PASSWORD=${tapo_password}
      - PORT=9333 # optional
    networks:
      - prometheus_localprom
networks:
  prometheus_localprom:
    external: true
